### ISSUE TITLE
Is it really possible to copy image?

### ISSUE THREAD

**Issue by davidborghi** [cmdvmd/common-clipboard#8]
Hello! 

Thank you for the awesome work!

> Note: Currently only works for the transfer of unicode text and images and may have a short (1-3 second) delay depending on internet speed and size of copied data on iOS devices due to the limitations of Apple Shortcuts

I tried with text and it worked flawlessly but It wasn't possible to use it with images (.jped and .png).

Should I adjust something or is this normal behaviour?

Thank you for your help and attention! 

I'm sorry for any inconvenience!

**Comment by cmdvmd** [comment]
This feature should work without making any changes. Make sure you are copying the image itself, not just the image file.

**Comment by davidborghi** [comment]
Hello! 

Thank you for your fast response! 

I've tried with multiple images and copying both images or image files but it didn't work, can I check what the problem is on my side?

Thank you for your help and attention! 

I'm sorry for any inconvenience!

**Comment by cmdvmd** [comment]
Where and how are you copying the images, and where are you trying to paste them?

Copying/pasting images have worked for me, I am able to copy an image from the photos app or the web, and I have been able to paste them into something like the notes app or Google Docs

**Comment by davidborghi** [comment]
> Where and how are you copying the images, and where are you trying to paste them?
> 
> Copying/pasting images have worked for me, I am able to copy an image from the photos app or the web, and I have been able to paste them into something like the notes app or Google Docs

I've tried copying images directly from ShareX window (using both copy image and image file) and from Windows Explorer.

I've tried to paste into WhatsApp Web (where the text worked fine) and OneNote app.

**Comment by cmdvmd** [comment]
I see. On Windows unfortunately it's not yet possible to paste images into some apps or websites because of the way I've interfaced with the clipboard on Windows. I've had success with things like the Google Docs website, though. I hope to one day fix these bugs, but this is the best I've been able to manage for now.

On a side note, you won't be able to copy images from Windows Explorer, you would have to open the file and copy the image itself. Copied images are also more functional in iOS if this helps your use case in any way, as I was able to paste an image onto the OneNote app on iOS.

Thank you so much for your interest in this project!
